# Generated by Django 2.0.7 on 2018-10-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Module_DeploymentMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_column='Event_Type', max_length=255)),
                ('event_startTime', models.CharField(db_column='Event_Start_Time', max_length=255)),
                ('event_endTime', models.CharField(db_column='Event_End_Time', max_length=255, null=True)),
                ('event_recovery', models.CharField(db_column='Event_Recovery_Time', max_length=255, null=True)),
                ('server_details', models.ForeignKey(db_column='Server_Details', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_DeploymentMonitoring.Server_Details')),
            ],
            options={
                'db_table': 'Event_Details',
                'managed': True,
            },
        ),
    ]
